In [1]:
# INTRO 1

import cv2 
from keras.models import load_model
import numpy as np

model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

[[3.1231627e-01 4.6979103e-06 6.9979738e-05 6.8760908e-01]]
[[8.4898478e-01 1.0696496e-05 5.8957834e-05 1.5094551e-01]]
[[8.8247091e-01 2.5063213e-05 2.3164479e-05 1.1748092e-01]]
[[9.7771180e-01 4.5995153e-06 4.0890882e-06 2.2279520e-02]]
[[8.3416778e-01 6.5687686e-06 3.1754826e-06 1.6582246e-01]]
[[9.7272444e-01 9.8990336e-07 3.9085626e-06 2.7270703e-02]]
[[9.4221127e-01 5.6912954e-06 1.9008436e-05 5.7764076e-02]]
[[9.4221127e-01 5.6912954e-06 1.9008436e-05 5.7764076e-02]]
[[9.8773181e-01 5.7127431e-07 1.2494610e-07 1.2267488e-02]]
[[9.4256628e-01 1.3477181e-06 2.7628769e-07 5.7432149e-02]]
[[9.6207356e-01 1.7748620e-05 5.6320960e-06 3.7903033e-02]]
[[9.2008466e-01 8.3617451e-06 2.5072700e-06 7.9904437e-02]]
[[9.2909878e-01 4.2823522e-06 7.1396944e-06 7.0889808e-02]]
[[9.8749441e-01 1.2697150e-06 3.6411316e-06 1.2500659e-02]]
[[9.8718435e-01 4.7914301e-07 2.1734288e-06 1.2813066e-02]]
[[9.7656333e-01 4.2262916e-05 1.3370446e-06 2.3393149e-02]]
[[9.8898357e-01 2.2800316e-06 2.4936583e

In [2]:
# INTRO 2

import cv2 
from keras.models import load_model
import numpy as np

model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction[0][0]) #Rock
    print(prediction[0][1]) #Paper
    print(prediction[0][2]) #Scissors
    print(prediction[0][3]) #Do Nothing
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

0.99877626
7.222161e-05
0.00035532788
0.0007961803
0.9999893
1.7483676e-07
2.3064568e-09
1.0558903e-05
0.9999957
1.9117253e-07
2.704459e-10
4.0956475e-06
0.99996865
8.4134825e-07
2.4846785e-09
3.0520507e-05
0.9999913
2.1669617e-07
7.914953e-10
8.485127e-06
0.999998
5.4291684e-07
1.1422434e-10
1.456607e-06
0.99998605
4.044374e-06
8.5964354e-11
9.870919e-06
0.99999654
7.220262e-07
1.9897183e-10
2.7073208e-06
0.99992573
8.437778e-06
1.2442548e-07
6.575069e-05
0.99999607
4.999691e-07
1.0390104e-08
3.392434e-06
0.99999857
4.0957036e-07
1.5029402e-08
1.0476866e-06
0.99998796
4.2204974e-06
5.8100174e-08
7.851221e-06
0.99999356
1.9782155e-07
2.6674982e-08
6.25529e-06
0.99999917
1.7466117e-07
4.669205e-10
6.0541413e-07
0.9999993
2.6791186e-08
2.7330202e-10
7.11083e-07
0.9999995
1.7750201e-08
3.7082636e-11
3.998275e-07
0.999998
3.736792e-08
9.667966e-11
1.9539575e-06
0.9999937
1.3950347e-06
2.7833813e-10
4.97143e-06
0.99998176
2.109776e-06
1.2738515e-08
1.6178166e-05
0.9999927
5.298945e-07
5.086

In [3]:
# INTRO 3

import cv2 
from keras.models import load_model
import numpy as np

model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    if prediction[0][0] > 0.5: #Rock
        print('Rock')
    elif prediction[0][1] > 0.5: #Paper
        print('Paper')
    elif prediction[0][2] > 0.5: #Scissors
        print('Scissors')
    else: #Nothing
        print('Nothing')
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Paper
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Rock
Scissors
Scissors
Scissors
Rock
Rock
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Rock
Scissors
Scissors
Rock
Rock
Paper
Paper
Paper
Paper
Paper
Paper
Scissors
Scissors
Paper
Scissors
Paper
Paper
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Scissors
Paper
Paper
Paper
Scissors
Paper
Paper
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Nothing
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Scissors
Scissors
Rock
Paper
Scissors
Sciss

In [5]:
import cv2 
from keras.models import load_model
import numpy as np

model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    if prediction[0][0] > 0.5: #Rock
        print('Rock')
    elif prediction[0][1] > 0.5: #Paper
        print('Paper')
    elif prediction[0][2] > 0.5: #Scissors
        print('Scissors')
    else: #Nothing
        print('Nothing')
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock


In [7]:
# INTRO 5

import cv2 
from keras.models import load_model
import numpy as np

model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

def pred_results():
        if prediction[0][0] > 0.5: #Rock
            return "Rock"
        elif prediction[0][1] > 0.5: #Paper
            return "Paper"
        elif prediction[0][2] > 0.5: #Scissors
            return "Scissors"
        else: #Nothing
            return "Nothing"


while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    
    results = pred_results()
    print(results)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock
Rock


In [32]:
import cv2
from keras.models import load_model
import numpy as np

cam = cv2.VideoCapture(0)
model = load_model('keras_model.h5')
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

def pred_results():
        if prediction[0][0] > 0.5: #Rock
            return "Rock"
        elif prediction[0][1] > 0.5: #Paper
            return "Paper"
        elif prediction[0][2] > 0.5: #Scissors
            return "Scissors"
        else: #Nothing
            return "Nothing"
                                                                                                                                                                                                
cv2.namedWindow("test")

img_counter = 0

while True:
    ret, frame = cam.read()
    if not ret:
        print("failed to grab frame")
        break
    cv2.imshow("test", frame)

    k = cv2.waitKey(1)
    if k%256 == 27:
        # ESC pressed
        print("Escape hit, closing...")
        break
    elif k%256 == 32:
        # SPACE pressed
        # model = load_model('keras_model.h5')
        # data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
        resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
        image_np = np.array(resized_frame)
        normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
        data[0] = normalized_image
        prediction = model.predict(data)
        # cv2.imshow('frame', frame)
        # Press q to close the windowq
        results = pred_results()
        print(results)
       
 
cam.release()
cv2.destroyAllWindows() 

Rock
Scissors
Rock
Paper
Paper
Escape hit, closing...


In [3]:
import time
import cv2
from keras.models import load_model
import numpy as np

cam = cv2.VideoCapture(0)
model = load_model('keras_model.h5')
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

cv2.namedWindow("test")

img_counter = 0

while True:
    ret, frame = cam.read()
    if not ret:
        print("failed to grab frame")
        break
    cv2.imshow("test", frame)

    k = cv2.waitKey(1)
    if k%256 == 27:
        # Press ESC to exit
        print("Escape hit, closing...")
        break
    elif k%256 == 32:
        # Press SPACE to start
        def countdown(t):
          while t: # while t > 0 for clarity 
            mins = t // 60
            secs = t % 60
            timer = '{:02d}:{:02d}'.format(mins, secs)
            print(timer, end="\r") # overwrite previous line 
            time.sleep(1)
            t -= 1
          print('Showing Results!!!')
        t = input("Enter the time in seconds: ") 
        countdown(int(t))
        # model = load_model('keras_model.h5')
        # data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
        resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
        image_np = np.array(resized_frame)
        normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
        data[0] = normalized_image
        prediction = model.predict(data)
        # cv2.imshow('frame', frame)
        # Press q to close the window
        results = pred_results()   
        print(results)
       
cam.release()
cv2.destroyAllWindows()

Start CountDown!!!
Paper
Escape hit, closing...


In [8]:
import time
import cv2
from keras.models import load_model
import numpy as np

cam = cv2.VideoCapture(0)
model = load_model('keras_model.h5')
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

cv2.namedWindow("test")

img_counter = 0

while True:
    ret, frame = cam.read()
    if not ret:
        print("failed to grab frame")
        break
    cv2.imshow("test", frame)

    k = cv2.waitKey(1)
    if k%256 == 27:
        # Press ESC to exit
        print("Escape hit, closing...")
        break
    elif k%256 == 32:
        # Press SPACE to start
        def countdown(t):
          while t: # while t > 0 for clarity 
            mins = t // 60
            secs = t % 60
            timer = '{:02d}:{:02d}'.format(mins, secs)
            print(timer, end="\r") # overwrite previous line 
            time.sleep(1)
            t -= 1
          print('Showing Results!!!')
        t = input("Enter the time in seconds: ") 
        countdown(int(t))
        # model = load_model('keras_model.h5')
        # data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
        resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
        image_np = np.array(resized_frame)
        normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
        data[0] = normalized_image
        prediction = model.predict(data)
        # cv2.imshow('frame', frame)
        # Press q to close the window
        results = pred_results()   
        print(results)
       
cam.release()
cv2.destroyAllWindows()

Showing Results!!!
Rock
Escape hit, closing...


In [7]:
def get_user_choice():
    user_input = input("Enter your input: ")
    return(user_input)
user_choice = get_user_choice()

def get_computer_choice():
        import random
        pred_list = ['Rock', 'Scissors', 'Paper']
        return(random.choice(pred_list))
Computer_choice = get_computer_choice()

def results():
        if user_choice == Computer_choice: #Rock
            return "Same Prediction"
        elif user_choice != Computer_choice: #Paper
            return "Different Prediction"
result = results()
print(result)

Different Prediction


In [15]:
import cv2
from keras.models import load_model
import numpy as np
import random

cam = cv2.VideoCapture(0)
model = load_model('keras_model.h5')
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

cv2.namedWindow("test")

img_counter = 0

while True:
    ret, frame = cam.read()
    if not ret:
        print("failed to grab frame")
        break
    cv2.imshow("test", frame)

    k = cv2.waitKey(1)
    if k%256 == 32:
        # SPACE pressed
        
        resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
        image_np = np.array(resized_frame)
        normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
        data[0] = normalized_image
        prediction = model.predict(data)
        
        def get_user_choice():
            user_input = input("Enter your input: ")
            return(user_input)
        user_choice = get_user_choice()
        
        def get_computer_choice():
            pred_list = ['Rock', 'Scissors', 'Paper', 'Nothing']
            return(random.choice(pred_list))
        computer_choice = get_computer_choice()
        
        def pred_results():
            if prediction[0][0] > 0.5: #Rock
                return "Rock"
            elif prediction[0][1] > 0.5: #Paper
                return "Paper"
            elif prediction[0][2] > 0.5: #Scissors
                return "Scissors"
            else: #Nothing
                return "Nothing"
        real_pred = pred_results()

        def get_winner():
            if (user_choice == real_pred) & (computer_choice != real_pred): #User Won
                return "User Won"
            elif (computer_choice == real_pred) & (user_choice != real_pred): # Computer Won
                return "Computer Won"
            elif (computer_choice == real_pred) & (user_choice == real_pred): # Computer and User Won
                return "Both Computer and User Won"
            else: # Neither Won
                return "No Winner yet! Try Again"
        result = get_winner()
        print(result)

    elif k%256 == 27:
        # ESC pressed
        print("Escape hit, closing...")
        break   
cam.release()
cv2.destroyAllWindows() 

User Won
Escape hit, closing...


In [12]:
import cv2
from keras.models import load_model
import numpy as np
import random

cam = cv2.VideoCapture(0)
model = load_model('keras_model.h5')
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

cv2.namedWindow("test")

img_counter = 0

while True:
    ret, frame = cam.read()
    if not ret:
        print("failed to grab frame")
        break
    cv2.imshow("test", frame)

    k = cv2.waitKey(1)
    if k%256 == 32: #SPACE pressed
        resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
        image_np = np.array(resized_frame)
        normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
        data[0] = normalized_image
        prediction = model.predict(data)
        
        def play():
            def get_user_choice():
                user_input = input("Enter your input: ")
                return(user_input)
            user_choice = get_user_choice()
            
            def get_computer_choice():
                pred_list = ['Rock', 'Scissors', 'Paper']
                return(random.choice(pred_list))
            computer_choice = get_computer_choice()
         
            def pred_results():
                if prediction[0][0] > 0.5: #Rock
                    return "Rock"
                elif prediction[0][1] > 0.5: #Paper
                    return "Paper"
                elif prediction[0][2] > 0.5: #Scissors
                    return "Scissors"
                else: #Nothing
                    return "Nothing"
            real_pred = pred_results()
         
            def get_winner():
                if (user_choice == real_pred) & (computer_choice != real_pred): #User Won
                     return "User Won"
                elif (computer_choice == real_pred) & (user_choice != real_pred): # Computer Won
                     return "Computer Won"
                elif (computer_choice == real_pred) & (user_choice == real_pred): # Computer and User Won
                     return "Both Computer and User Won"
                else: # Neither Won
                     return "No Winner yet! Try Again"
            result = get_winner()
        print(get_winner())

    elif k%256 == 27:
        # ESC pressed
        print("Escape hit, closing...")
        break   
cam.release()
cv2.destroyAllWindows() 

No Winner yet! Try Again
No Winner yet! Try Again
No Winner yet! Try Again
Escape hit, closing...


In [ ]:

# Wrong
import cv2
from keras.models import load_model
import numpy as np
import random

cam = cv2.VideoCapture(0)
model = load_model('keras_model.h5')
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

cv2.namedWindow("test")

img_counter = 0

while True:
    ret, frame = cam.read()
    if not ret:
        print("failed to grab frame")
        break
    cv2.imshow("test", frame)

    k = cv2.waitKey(1)

    
         def play():
             if k%256 == 32: # SPACE pressed
                 resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
                 image_np = np.array(resized_frame)
                 normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
                 data[0] = normalized_image
                 prediction = model.predict(data)
                 
                 def get_user_choice():
                     user_input = input("Enter your input: ")
                     return(user_input)
                 user_choice = get_user_choice()
            
                 def get_computer_choice():
                     pred_list = ['Rock', 'Scissors', 'Paper']
                     return(random.choice(pred_list))
                 computer_choice = get_computer_choice()
         
                 def pred_results():
                     if prediction[0][0] > 0.5: #Rock
                         return "Rock"
                     elif prediction[0][1] > 0.5: #Paper
                         return "Paper"
                     elif prediction[0][2] > 0.5: #Scissors
                         return "Scissors"
                     else: #Nothing
                         return "Nothing"
                 real_pred = pred_results()
         
                 def get_winner():
                     if (user_choice == real_pred) & (computer_choice != real_pred): #User Won
                         return "User Won"
                     elif (computer_choice == real_pred) & (user_choice != real_pred): # Computer Won
                         return "Computer Won"
                     elif (computer_choice == real_pred) & (user_choice == real_pred): # Computer and User Won
                         return "Both Computer and User Won"
                     else: # Neither Won
                         return "No Winner yet! Try Again"
                 result = get_winner()
             
                 return result     

             elif k%256 == 27: # ESC pressed
                 print("Escape hit, closing...")
             break   


cam.release()
cv2.destroyAllWindows() 

In [ ]:
def findout_winner(user_move, Computer_move):
    
    if user_move == Computer_move:
        return "Tie"   

    elif user_move == "rock" and Computer_move == "scissor":

        return "User"

    elif user_move == "rock" and Computer_move == "paper":
        return "Computer"

    elif user_move == "scissor" and Computer_move == "rock":
        return "Computer"

    elif user_move == "scissor" and Computer_move == "paper":
        return "User"

    elif user_move == "paper" and Computer_move == "rock":
        return "User"

    elif user_move == "paper" and Computer_move == "scissor":
        return "Computer"
