In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model_2.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

[[2.8744426e-01 2.2356544e-02 6.8225781e-05 6.9013095e-01]]
[[1.3396975e-01 2.5393734e-02 1.1750010e-04 8.4051907e-01]]
[[4.6666431e-01 3.6958782e-03 2.9702453e-05 5.2961010e-01]]
[[0.54221195 0.01383099 0.00064011 0.4433169 ]]
[[5.4997325e-01 4.2780926e-03 1.3800438e-04 4.4561070e-01]]
[[0.31165484 0.00740102 0.00087342 0.6800707 ]]
[[1.0005690e-01 2.3706104e-03 4.5539771e-04 8.9711708e-01]]
[[3.9085078e-01 1.5002661e-03 3.0185908e-04 6.0734713e-01]]
[[2.2452535e-02 1.4706826e-03 7.5467851e-04 9.7532213e-01]]
[[1.04720436e-01 2.93811760e-03 5.94709883e-04 8.91746759e-01]]
[[0.63883895 0.00486174 0.0013814  0.35491797]]
[[0.01401516 0.0452578  0.00320673 0.93752027]]
[[0.05456547 0.0014185  0.00211139 0.9419047 ]]
[[0.2704793  0.00372456 0.00329956 0.7224966 ]]
[[0.10672026 0.00233738 0.00230695 0.8886353 ]]
[[0.52442497 0.00061502 0.00059071 0.4743694 ]]
[[7.7018148e-01 7.2713965e-04 2.4432910e-04 2.2884709e-01]]
[[0.507037   0.00458521 0.0018546  0.48652327]]
[[0.1478271  0.00341445 

KeyboardInterrupt: 

In [2]:
import time
def countdown(t):
    while t:
        # This showing the time in seconds
        mins,secs = divmod(t, 60)
        # second I've to format the mins, secs time format
        # 2d means fo rmats to 2 characters using padding
        timer = f"{mins}:{secs:02d}"
        # \r: To make next time into beginning of the current line
        print(timer,end = "\r")
        # Program wait for 1 second
        time.sleep(1)
        t-=1
    print("Timer Completed!")

t = input("Enter the time in seconds:")
countdown(int(t))

KeyboardInterrupt: Interrupted by user